### ISSUE TITLE
Tagged releases and changelog

### ISSUE THREAD

**Issue by baimafeima** [Dako300/BasicTV#5]
Could you tag your releases and make the changelog directly visible in your GitHub releases? This would increase transparency for potential users and distribution maintainers. Something like https://skywinder.github.io/github-changelog-generator/ could be used to generate the changelog based on merged PRs and closed issues since the last release tag.

**Comment by Dako300** [comment]
Good idea. I think the project has matured enough to include some formal pre-releases, and expand beyond just myself. Taking a look at github_changelog_generator now.

**Comment by baimafeima** [comment]
Thanks a lot, looks great!
